FROM node:20.5.1-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
WORKDIR /app

COPY . .
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

FROM base AS backend
WORKDIR /app/packages/backend
EXPOSE 8090
CMD [ "pnpm", "run", "dev" ]

FROM base AS studio
WORKDIR /app/packages/backend
EXPOSE 4980
CMD [ "pnpm", "run", "db:studio" ]

FROM base AS frontend
WORKDIR /app/packages/frontend
EXPOSE 5173
CMD [ "pnpm", "run", "dev", "--host" ]
